name: flutter_movie_app
description: Aplicación para streaming de películas caseras
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  video_player: ^2.6.1
  chewie: ^1.5.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/